version: '2.2'

services:

  #PHP Service
  app:
    container_name: slimtest_oauth_app
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    container_name: slimtest_oauth_webserver
    image: nginx:alpine
    ports:
      - "${WEBSERVER_PORT}:80"
      - "${WEBSERVER_PORT_SEC}:443"
    volumes:           
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  mysql:
    container_name: slimtest_oauth_mysql
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - 'dbdata:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local 